// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApi.Data;

#nullable disable

namespace MyApi.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240819133456_UpdateFinancesTable")]
    partial class UpdateFinancesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApi.Caris.Cari", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("id"));

                    b.Property<decimal?>("alacak")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("banka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bina_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("borc")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("daire_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("il")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ilce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mahalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sokak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tel_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ulke")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Caris");
                });

            modelBuilder.Entity("MyApi.Finances.Finance", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Cariid")
                        .HasColumnType("int");

                    b.Property<string>("aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("cari_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("miktar")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<string>("odeme_tipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("Cariid");

                    b.ToTable("Finances");
                });

            modelBuilder.Entity("MyApi.Users.User", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("id"));

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyApi.Finances.Finance", b =>
                {
                    b.HasOne("MyApi.Caris.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("Cariid");

                    b.Navigation("Cari");
                });
#pragma warning restore 612, 618
        }
    }
}
